kind: pipeline
type: exec
name: backend

steps:
  - name: 'git pull'
    commands:
      - cd /var/www/projects/pet-adopter-spring
      - git pull
  - name: 'maven package'
    commands:
      - cd /var/www/projects/pet-adopter-spring
      - mvn package
  - name: 'docker compose'
    commands:
      - cd /var/www/projects/pet-adopter-spring
      - docker-compose up -d --build
