version: '3.8'

services:
  pet-adopter:
    container_name: pet-adopter
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

networks:
  default:
    external:
      name: external-network
