spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet-adopter-spring
    username: webdev
    password: welcome
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql